### ISSUE TITLE
Error on Options open

### ISSUE THREAD

**Issue by artquest** [vitalikp/flagfox#2]
"XML Parsing Error: undefined entity" instead of options window.
Win 7 x64, FF 56.0.2

**Comment by vitalikp** [comment]
https://github.com/vitalikp/flagfox/issues/1#issuecomment-364305827

**Comment by BlohoJo** [comment]
I didn't try the options window before (5.2.4), but with the 5.2.5 version posted above, it is working for me.

**Comment by vitalikp** [comment]
Issue fixed by commit 881c514b906d65aaf4b7444278aba193435f2216

**Comment by BlohoJo** [comment]
[Release](https://github.com/vitalikp/flagfox/releases) is still at ESR 5.2.4 version, might want to update it to latest commit! :)

**Comment by vitalikp** [comment]
I plan to make release on Tuesday:)
